name: Node.js CI with Yarn 4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Setup Node.js
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      # Install specific Yarn version
      - name: Install Yarn 4.9.2
        run: |
          corepack enable
          corepack install
      
      # Verify Yarn version
      - name: Check Yarn version
        run: yarn --version
      
      # Install dependencies (allow lockfile migration on first run)
      - name: Install dependencies
        run: yarn install
      
      # Commit updated lockfile if this is a migration
      - name: Check for lockfile changes
        id: lockfile-check
        run: |
          if git diff --quiet yarn.lock; then
            echo "lockfile-changed=false" >> $GITHUB_OUTPUT
          else
            echo "lockfile-changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit lockfile migration
        if: steps.lockfile-check.outputs.lockfile-changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add yarn.lock
          git commit -m "Migrate lockfile to Yarn 4 format" || echo "No changes to commit"
          git push
      
      # Verify installation worked
      - name: Verify installation
        run: yarn list --depth=0
      
      # Only publish on main branch pushes
      - name: Publish Package to npm
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
