name: Node.js CI with Yarn 4 (Simple)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Setup Node.js
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      # Enable Corepack and install Yarn 4
      - name: Setup Yarn 4
        run: |
          corepack enable
          corepack install
      
      # Verify Yarn version
      - name: Check Yarn version
        run: yarn --version
      
      # Install dependencies (allow lockfile creation for CI)
      - name: Install dependencies
        run: yarn install
      
      # Check package availability (optional)
      - name: Check package availability
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "Checking availability of package: $PACKAGE_NAME"
          if npm view "$PACKAGE_NAME" > /dev/null 2>&1; then
            echo "Warning: Package $PACKAGE_NAME already exists on npm"
          else
            echo "Package name $PACKAGE_NAME is available"
          fi
      
      # Only publish on main branch pushes
      - name: Publish Package to npm
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
